### ISSUE TITLE
Cannot broadcast IPV6 DNS for SLAAC devices.

### ISSUE THREAD

**Issue by dsanke** [openwrt/odhcpd#103]
Switch from radvd to odchpd,found cannot broadcast ipv6 dns for stateless devices like radvd.

**Comment by dedeckeh** [comment]
odhcpd uses the RECURSIVE DNS option (RFC8106) in RA messages to pass the IPv6 DNS server(s) to stateless devices (see https://git.lede-project.org/?p=project/odhcpd.git;a=blob;f=src/router.c;h=feae5c7e1b28516f28e483645ffffdfade974418;hb=HEAD#l419). Can you share details why this does not seem to work for you ?
