### ISSUE TITLE
Feature Reqeust: odhcpd in 17.04.4 control of Unsolicited RA timing (see RFC 7772)

### ISSUE THREAD

**Issue by cvmiller** [openwrt/odhcpd#107]
Based on RFC 7772, saving the battery life of mobile devices, it would be good to have control of how often RAs are sent and the maximum life time. From the RFC:

> In order to limit the amount of power used to receive Router
>       Advertisements to, say, 2% of idle power (i.e., to impact idle
>       battery life by no more than 2%), the average power budget for
>       receiving RAs must be no more than 0.1 mA, or approximately 7 RAs
>       per hour.

> Thus, the minimum lifetimes for
>       RA configuration parameters such as default router lifetime might
>       reasonably be 5-10 times the RA period, or roughly 45-90 minutes.
>

**Comment by dedeckeh** [comment]
As described in the [README](https://git.openwrt.org/?p=project/odhcpd.git;a=blob;f=README;h=0c562e6faed472dadf8170a9e4e83f214cb054a8;hb=HEAD) the transmission interval for unsolicited RAs can be tweaked by the uci parameters ra_mininterval and ra_maxinterval; default router lifetime can be tweaked via the uci parameter ra_lifetime

**Comment by cvmiller** [comment]
Great, I'll see about updating the wiki documentation to match the README. Thanks.
