### ISSUE TITLE
odhcpd sends incorrect DHCv6 reconfigure HMAC

### ISSUE THREAD

**Issue by rsmarples** [openwrt/odhcpd#11]
in src/dhcpv6-ia.c, send_reconf the md5 hmac hashing is wrong

I added this test segment into the function, using the 1st test from RFC2202

```
        const uint8_t text[] = "Hi There";
        uint8_t key[16];
        uint8_t digest[16];

        for (size_t i = 0; i < 16; i++)
                key[i] = 0x0b;

        memcpy(secretbytes, key, sizeof(secretbytes));

        for (size_t i = 0; i < sizeof(secretbytes); ++i)
                secretbytes[i] ^= 0x36;

        md5_begin(&md5);
        md5_hash(secretbytes, sizeof(secretbytes), &md5);
        md5_hash(text, 8, &md5);
        md5_end(digest, &md5);

        for (size_t i = 0; i < sizeof(secretbytes); ++i) {
                secretbytes[i] ^= 0x36;
                secretbytes[i] ^= 0x5c;
        }

        md5_begin(&md5);
        md5_hash(secretbytes, sizeof(secretbytes), &md5);
        md5_hash(digest, 16, &md5);
        md5_end(digest, &md5);

        printf ("test digest: ");
        for(size_t i = 0; i < 16; i++)
                printf("%.2x", digest[i]);
        printf ("\n");
        printf ("expected   : 9294727a3638bb1c13f48ef8158bfc9d\n");
```

I got this digest instead:
da401ca2fffa2fcecc52f0a6027d56a1

A quick fix was to add md5.c, md5.c and hmac_md5 from dhcpcd source tree and use them instead.

Please ensure your hashing passes RFC2202 and add test suites.
Otherwise the reconfigure function work well with the latest dhcpcd fossil code available from here:
http://roy.marples.name/projects/dhcpcd/timeline

**Comment by sbyx** [comment]
Thanks, fixed now. Good to see that another open-source project implements dhcpv6-reconfigure ;)
Also nice project that you have there.

**Comment by rsmarples** [comment]
Confirmed fix!
Thanks for the kind words. It's good to see an open source server that implements dhcpv6-reconfigure as well :) Do you support the same method for DHCPv4?

I wasn't able to test the other authentication methods (token, delayed, delayed + realm) as it wasn't obvious how to configure that. Can you tell me how so I can test dhcpcd against it please?

Thanks!

**Comment by sbyx** [comment]
Sorry, I don't implement any other auth atm.

I mainly implemented reconfigure (+reconfigure auth) to comply with RFC 6204 / 7084 in the DHCPv6-client (https://github.com/sbyx/odhcp6c) for OpenWrt's IPv6-stack. The server part I did mainly to test the client side. Unfortunately both were equally broken until today ;)

Anyway I don't implement the DHCPv4-equivalent mainly for the lack of authentication right now and there not being a Reconfigure-Auth equivalent and not really wanting to use any other authentication mechanism. Also in our traditional environments DHCPv4-addresses are rather static as we do NAT so not sure if that makes much sense.

I was wondering to patch in optional dhcpv4-reconfigure support into the busybox dhcp-client without authentication as some ISPs might be interested in that.

**Comment by rsmarples** [comment]
You've not read [RFC6704](http://tools.ietf.org/html/rfc6704) then :)
If you read the DHCP authentication RFCs you'll see that the payload is identical for DHCPv4 and DHCPv6 (option code and length sizes not withstanding). This basically means that all authentication mechanisms are available for DHCPv4 and DHCPv6.
