### ISSUE TITLE
***SECURITY ISSUES

### ISSUE THREAD

**Issue by marksaitis** [openwrt/odhcpd#125]
Hi,

I have this config to ensure DHCP6 is disabled. I also disabled all possible dhcp6 options for all possible interfaces over sysctl.conf.
config dhcp 'lan'
        option interface 'lan'
        option leasetime '12h'
        option dhcpv4 'server'
        option start '1'
        option limit '100'
        option ra 'disabled'
        option dhcpv6 'disabled'
        option ndp 'disabled'
        option ra_default '2'
        option ra_management '2'

And whatever I do, this beast has enough courage to go and listen on a RAW socket!!! What is going on guys? Completely unacceptable. 

raw        0      0 ::%1:58                 ::%4448412:*            58          1155/odhcpd
raw        0      0 ::%1:58                 ::%4448412:*            58          1155/odhcpd

Regards

**Comment by dedeckeh** [comment]
Well you could have stated that in a polite way as well
Anyway thx for your observations

**Comment by marksaitis** [comment]
Sorry, after spending few hours on this I got a bit frustrated. I don't want odhcpd to use any ipv6 for my application whatsoever. Not a matter of questions here. I read all docs - disabled all ipv6 related stuff - and nothing. It still dares to open raw sockets. To me it is a security issue. Does anyone have a clue here? I am considering going back to dnsmasq - something what can be controlled at least.

**Comment by dedeckeh** [comment]
Fixed in commits https://github.com/openwrt/odhcpd/commit/c6dae8e6b2a82dca6e2e00e17b0bc968a504d7fc and https://github.com/openwrt/odhcpd/commit/65a9519fb295d8f5748fc69962be1666985011fe

**Comment by marksaitis** [comment]
> Fixed in commits [c6dae8e](https://github.com/openwrt/odhcpd/commit/c6dae8e6b2a82dca6e2e00e17b0bc968a504d7fc) and [65a9519](https://github.com/openwrt/odhcpd/commit/65a9519fb295d8f5748fc69962be1666985011fe)

Wow. I am impressed at the speed of resolution and action here. Will go back to using odhcpd! Thanks a lot and have a great day!
