### ISSUE TITLE
Wrong loglevels

### ISSUE THREAD

**Issue by damnms** [openwrt/odhcpd#127]
I am facing currently some wierd problem with my mobile phone (Lineageos 16). I was able to connect to my Router (Solidrun Clearfog Pro) with Openwrt 18.06.02. But since 2 days or so i can not connect anymore. I see the SIDs of my wifi and the neighbours but i can not connect to mine.

So i checked the logs with logread -f
First for my tablet (where everything works)
```
daemon.notice odhcpd[1642]: Got DHCPv4 request 
daemon.warn odhcpd[1642]: received DHCPV4_MSG_REQUEST from 00:04:4b:56:ec:15 (<- why is this a warn?!)
daemon.err odhcpd[1642]: Sent DHCPV4_MSG_ACK to 00:04:4b:56:ec:15 - 192.168.7.161 (<- and why is this an error=?!)
```

Then the same with my mobile phone:
```
daemon.notice odhcpd[1642]: Got DHCPv4 request 
daemon.warn odhcpd[1642]: received DHCPV4_MSG_INFORM from d0:50:99:81:35:1f 
daemon.err odhcpd[1642]: Sent DHCPV4_MSG_ACK to ff:ff:ff:ff:ff:ff - 255.255.255.255 (<- again, an error. Does this mean: sending a broadcast for DHCPV4_MSG_ACK is an error?)
```

**Comment by dedeckeh** [comment]
Fixed in commit https://github.com/openwrt/odhcpd/commit/f1c6088328cb5ad578ca187aacf4c8dd51970c93
