### ISSUE TITLE
dhcp_option being parsed/utilized?

### ISSUE THREAD

**Issue by ghost** [openwrt/odhcpd#130]
I hope it did not miss it from the documentation but it is unclear to me whether

`list dhcp_option` in /etc/config/dhcp is being parsed/utilized by `odhcpd` or only `dnsmasq`?

If not than how to announce such option, e.g. for a ntp server (`list dhcp_option '42,ip'`) with `odhcpd`?

**Comment by dedeckeh** [comment]
Handling of the uci dhcp_option parameter is not supported in odhcpd; at the moment there's no support to configure dhcp options

**Comment by ghost** [comment]
Thanks for the clarification. Though it seems a few options are catered for in `odhcpd`

(3) = `option router`
(6) = `option/list dns`
(119) = `option domain`

(42) ntp server though is not. Can such be suggested as feature addition?

**Comment by dedeckeh** [comment]
Correct odhcpd supports the options broadcast (28), mtu (26), dns (6), router (3) and domain (119)
Of course ntp server can be suggested as feature addition
