### ISSUE TITLE
About implement rfc2461

### ISSUE THREAD

**Issue by Devinchai** [openwrt/odhcpd#137]
I want implement rfc2461 requirement.
when do you implement in odhcpd?

rfc2461 :
6.2.4.  Sending Unsolicited Router Advertisements 
 For the first few advertisements (up to
   MAX_INITIAL_RTR_ADVERTISEMENTS) sent from an interface when it
   becomes an advertising interface,

**Comment by dedeckeh** [comment]
Supported in commit https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=752fc2c278dc01f0b3ed2faf67a11f9bc1f3c627
