### ISSUE TITLE
valid time is expire, but dhcpv6 not release  address

### ISSUE THREAD

**Issue by Devinchai** [openwrt/odhcpd#141]
Dear @dedeckeh 
I set 2 dhcpv6 address pool; assign to PC A and PC B.
but when I pull out PC A,and wait for it valid time expire, 
then insert another PC C, it not assign dhcpv6 address .

I guess function "valid_until_cb" in dhcpv6-ia.c,
whether change this (a->length == 128 && a->clid_len == 0))
to 
(a->length == 128 && a->clid_len > 0))

**Comment by dedeckeh** [comment]
I fail to understand the issue; do you expect the address assigned to PC A to be assigned to PC C ? And if yes why do you expect this ?

**Comment by Devinchai** [comment]
@dedeckeh 
    PC A 's address not be released all the time , so PC C not get this address（only configure two address）,the reason it wasn't released is because  a->clid_len>0 .

**Comment by dedeckeh** [comment]
Are you talking about static leases ? If not I fail to understand how you can create a pool with only two IPv6 addresses ...

**Comment by Devinchai** [comment]
@dedeckeh ,
I modified function "assign_na", limit it assign only  two  address pool .

**Comment by Devinchai** [comment]
@dedeckeh ,
 I do not understand where is dhcp's address released?

**Comment by dedeckeh** [comment]
It happens here https://github.com/openwrt/odhcpd/blob/master/src/dhcpv6-ia.c#L763

**Comment by Devinchai** [comment]
@dedeckeh ，
 PC A get ipv6 address  by dhcpv6 ,but I pull the PC A cable，the address not be released all the time in iface->ia_assignments,  when the PC A address is released ?

I add log in function "valid_until_cb":
add log patch:
![add_log](https://user-images.githubusercontent.com/49850957/63846960-69a70200-c9bf-11e9-8240-e54b80a16387.png)

output and print log:
![print_log](https://user-images.githubusercontent.com/49850957/63847159-c99da880-c9bf-11e9-82bc-3fedbec23b24.png)

**Comment by dedeckeh** [comment]
Thanks for bringing this up; fixed in https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=94a1c942315f6b3c2870cf744114bb133f209799
