### ISSUE TITLE
route management issue with  IPv6 PD

### ISSUE THREAD

**Issue by madires** [openwrt/odhcpd#149]
Hi!

While setting up IPv6 PD with OpenWRT 18.06.4 I found several issues. This one is about the route management for PD. If odhcpd assigns PD prefixes to clients it adds route entries accordingly. But if the lease for a prefix expires odhcpd doesn't remove the route entry.

Cheers,
Markus

**Comment by dedeckeh** [comment]
Did you check if this issue is still present in the latest version of odhcpd ?

**Comment by madires** [comment]
Hi!

No, just with the version coming with OpenWRT 18.06.4.

Cheers,
 Markus

**Comment by dedeckeh** [comment]
Fixed in commit https://git.openwrt.org/?p=project/odhcpd.git;a=commitdiff;h=b413d8a13ad8d8bdc2e5bc700e9bae9b31232779
