### ISSUE TITLE
overly verbose logging

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/odhcpd#150]
My logs are filling with messages like:

```
odhcpd DHCPV6 SOLICIT IA_NA from [redacted] on br-lan: ok [redacted]::f2c/128 [redacted]::f2c/128
```

which seems to come from https://github.com/openwrt/odhcpd/blob/e76ad06d01d31fff4c482974138d2c4566e264cf/src/dhcpv6-ia.c#L1068-L1069

Is this really  **A condition requiring special handling**, per the definition of `LOG_NOTICE` at https://pubs.opengroup.org/onlinepubs/7908799/xsh/syslog.h.html?  This kind of log message seems more like `LOG_INFO` if not `LOG_DEBUG` even.

I wonder how many other `LOG_NOTICE` messages really are `LOG_INFO` or `LOG_DEBUG`.  Perhaps an audit and some adjustment is necessary.

**Comment by brianjmurrell** [comment]
Any thoughts on this?

**Comment by brianjmurrell** [comment]
Hello?

**Comment by dedeckeh** [comment]
I've optimized the syslog priority values in commit https://git.openwrt.org/?p=project/odhcpd.git;a=commitdiff;h=d60f0a6284e8f5fac733a1b269ea614ccdf47fcd

**Comment by brianjmurrell** [comment]
Looks promising!

I don't suppose there's any chance of that getting into an 18.06.x release is there?

**Comment by dedeckeh** [comment]
Backports to 18.06.x are only done for critical and security issues; I don't think this is the case here.
As 19.07.x is the latest stable release now I've backported the patch in commit https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=1f1867dd9bb98a6cbb6203c8574e747305f8a7ae

**Comment by brianjmurrell** [comment]
Hrm.  I checked yesterday before writing my comment and 19.07.x was still in (second) RC stage, so not quite "latest stable" I don't think.  https://openwrt.org/ still says that.

But your point on backports to 18.06 is taken.
