### ISSUE TITLE
Enable IGMP snooping error

### ISSUE THREAD

**Issue by 9000000** [openwrt/odhcpd#157]
When I turned this option on, the modem kept restarting
I have been in this condition for quite a long time

Please fix this error

Xiaomi r3g v1 OpenWrt SNAPSHOT r13573-03a0b7b7e5

**Comment by dedeckeh** [comment]
I cannot follow what is failing as odhcpd does not touch any IGMP snooping settings.
You will have to be more clear what is failing and explain the relationship to any setting odhcpd is touching

**Comment by dedeckeh** [comment]
I will close this issue for now; feel free to re-open if more info can be provided
