### ISSUE TITLE
send ACK to wrong ip address

### ISSUE THREAD

**Issue by kaffeenerd** [openwrt/odhcpd#16]
client gets ip address, then i set a static lease for it

client asks for it's old address again (192.168.1.107), server says ACK, but sends the packet to it's new address (.207) instead saying NACK to the old address

17:51:28.249991 IP (tos 0x0, ttl 128, id 9538, offset 0, flags [none], proto UDP (17), length 328)
    192.168.1.107.68 > 192.168.1.1.67: BOOTP/DHCP, Request from 7c:xx:xx:xx:xx:b0, length 300, xid 0x2e4f8501, Flags [none]
          Client-IP 192.168.1.107
          Client-Ethernet-Address 7c:xx:xx:xx:xx:b0
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: Request
            Client-ID Option 61, length 7: ether 7c:xx:xx:xx:xx:b0
            Hostname Option 12, length 7: "clientname"
            FQDN Option 81, length 10: "clientname"
            Vendor-Class Option 60, length 8: "MSFT 5.0"
            Parameter-Request Option 55, length 13: 
              Subnet-Mask, Domain-Name, Default-Gateway, Domain-Name-Server
              Netbios-Name-Server, Netbios-Node, Netbios-Scope, Router-Discovery
              Static-Route, Classless-Static-Route, Classless-Static-Route-Microsoft, Option 252
              Vendor-Option
17:51:28.252400 IP (tos 0xc0, ttl 64, id 811, offset 0, flags [none], proto UDP (17), length 576)
    192.168.1.1.67 > 192.168.1.207.68: BOOTP/DHCP, Reply, length 548, xid 0x2e4f8501, Flags [none]
          Your-IP 192.168.1.207
          Server-IP 192.168.1.1
          Client-Ethernet-Address 7c:xx:xx:xx:xx:b0
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: ACK
            Server-ID Option 54, length 4: 192.168.1.1
            Lease-Time Option 51, length 4: 7200
            RN Option 58, length 4: 3600
            RB Option 59, length 4: 6300
            Subnet-Mask Option 1, length 4: 255.255.255.0
            Hostname Option 12, length 7: "clientname"
            BR Option 28, length 4: 192.168.1.255
            MTU Option 26, length 2: 1500
            T119 Option 119, length 8: 108224877,1630745088
            Default-Gateway Option 3, length 4: 192.168.1.1
            Domain-Name-Server Option 6, length 4: 192.168.1.1

**Comment by sbyx** [comment]
Can you retry with the latest version please?

**Comment by mehlis** [comment]
@kaffeenerd with https://github.com/sbyx/odhcpd/pull/21 your device should get a NAK _with_ the _right_ IP to use.

so you should see DHCP REQUEST (with wrong IP) and DHCP NAK (with a working configuration attached). In case your client does not parse the NAK in a way iDevices and Android, then it should issue a new round trip with DHCP DISCOVER etc. I hope both cases are fixed now...
