### ISSUE TITLE
No DHCPv6 lease neither IPv6-PD if leasetime < 12h

### ISSUE THREAD

**Issue by vevere** [openwrt/odhcpd#170]
Hi,

If you reduce (with Lucy or on the /etc/config DHCP file) the lease time to anythin < 12h odhcpd don't affect any lease to any client (and no more IPv6-PD to any downstream router)

- tested on many routers (QCA, Rampis, X86_64) with OpenWRT > 20.x (21.02.0-rc* or any 21.* snapshot)
- reproductible : 
   - yes, with any fresh install
   - no need to connect the WAN side
   - public scope not even needed, LUA is enough to reproduce 
   - Under NetWork / Interface / LAN / DHCP Server set the Lease time to anything lower than 10h
   - on any LAN host : do an IP release/renew => you loose the GUA address
   - on any downstream OpenWRT router : restart the WAN interface => no more IPv6-PD on the WAN iface

Lease = 12h
![lease 12h](https://user-images.githubusercontent.com/26826853/122361047-300a0700-cf57-11eb-8ced-b347acc0d377.jpg)

Lease = 1h
![lease 1h](https://user-images.githubusercontent.com/26826853/122361086-39936f00-cf57-11eb-9a96-6515b331d84b.jpg)

**Comment by vevere** [comment]
Sorry for the typo:
   - Under NetWork / Interface / LAN / DHCP Server set the Lease time to anything lower than 12h
instead of
   - Under NetWork / Interface / LAN / DHCP Server set the Lease time to anything lower than 10h

**Comment by dedeckeh** [comment]
Fixed in commit https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=bc9d317f2921ae6b529f2c9f8de79b75992e206f
