### ISSUE TITLE
PREF64 support for NAT64

### ISSUE THREAD

**Issue by tiagogaspar8** [openwrt/odhcpd#182]
Hi all,

I have a NAT64 network and I read that there is a RA extension to advertise NAT64 network prefix and I'd like to know if there is support or planned support for RFC 8781 in odhcpd.

Thanks!

**Comment by dedeckeh** [comment]
From my side there're no concrete plans to implement support for this rfc

**Comment by tiagogaspar8** [comment]
Thanks for the reply.
Since OpenWrt has support for nat64 with jool it is an interesting idea, but since I believe no router advertisement daemons have support for this we're not that behind 😅
I have also found this, which is very interesting:
https://github.com/lcolitti/radvd-pref64

**Comment by zajdee** [comment]
pref64 support was just merged into `radvd`; @oskar456 recently shared a dirty hack of pref64 support in odhcpd, maybe it could be used as a good starting point for a clean implementation?

https://gist.github.com/oskar456/5183dee566416101727331bda30dd816

**Comment by aalmenar** [comment]
Any reason for this pull request not being merged ?, this is the only piece i need to have full automagic ipv6 only network with clat
