### ISSUE TITLE
Resolving DHCP assigned LAN machines

### ISSUE THREAD

**Issue by mikejuni** [openwrt/odhcpd#24]
Again another dnsmasq feature that odhcpd doesn't have that I'd like to report.

When dnsmasq is used as the DHCP server, it allows resolving of LAN machines that it has assigned IP address (not a surprise, as it is running within the same program), even for IPv6. It means that if I do a "ping6 machine.lan" it can properly resolve to a IPv6 address.

However, since there is no communication between odhcpd and dnsmasq, it doesn't work. One way to fix this is probably to generate a host file in /var/run directory and configure dnsmasq to read it. (Perhaps if dnsmasq can read lease file format that odhcpd generates it can also work now with a simple configuration change).

**Comment by sbyx** [comment]
This feature should work well for quite a while already. See /tmp/hosts/odhcpd but please let me know if there are issues with it.

**Comment by ott** [comment]
If odhcpd requires dnsmasq for this feature, why should you run odhcpd in the first place?

At the moment the leasetrigger script receives no arguments, so it would have to remember all entries in the old lease file and find the differences. If the leasetrigger script updates DNS records via DNS UPDATE (RFC 2136) and [dudders](http://dudders.sourceforge.net/), nsupdate or ddns-scripts for example, it has to have copy either in a seperate daemon or file and essentially duplicates the state that is already available in odhcpd. I think it would be better to add an additional callback in `dhcpv6_handle_ia` and `dhcpv4_lease` to handle just a single update.
