### ISSUE TITLE
Errors on kernel without IPv6 support

### ISSUE THREAD

**Issue by roger-** [openwrt/odhcpd#34]
odhcpd on an OpenWrt image with IPv6 removed gives the following errors:

```
Fri Jan  2 00:40:23 2015 daemon.err odhcpd[1054]: Failed to open routing table: No such file or directory
Fri Jan  2 00:40:23 2015 daemon.err odhcpd[1054]: Unable to open raw socket: Address family not supported by protocol
```

Is this expected? Seems like the code assumes IPv6 support is always present.

(I'm also losing connectivity, but I'm not sure if that's odhcp related.)

**Comment by probonopd** [comment]
I have the same issue

**Comment by baccrog** [comment]
I ended up just removing odhcpd and using dnsmasq.

**Comment by roger-** [comment]
I ended up just removing odhcpd and using dnsmasq.

**Comment by sbyx** [comment]
You don't need odhcpd on non-standard IPv4-only installations anyway since dnsmasq is still the default DHCPv4 server. I will address once I can work on the refactored version again.

**Comment by jbergstroem** [comment]
Just ran into this on a recent OpenWrt install as well.
