### ISSUE TITLE
not seeing a /60 on comcast

### ISSUE THREAD

**Issue by dtaht** [openwrt/odhcpd#42]
I am building from trunk and requesting a /60 via either ip6assign or reqprefix...

Not getting one. I used to get one. I will check to see if I get one from an older box on the same link.

Have a horde of other dhcp issues...

**Comment by dtaht** [comment]
This is me only apparently getting a /64

http://snapon.lab.bufferbloat.net/~d/comcast_dhcp_issues.cap

not quite relevant to this but this is the ipv4 behavior without rebooting the darn modem:

https://dev.openwrt.org/ticket/19603#ticket

**Comment by sbyx** [comment]
Edit: In the PCAP two different DHCPv6 servers are advertising a prefix with different length (one /64, one /60) each.

It seems the server advertising the /64 announces a preference of 255 and the one with the /60 a preference of 0.

According to https://tools.ietf.org/html/rfc3315#section-17.1.2

"If the client
   receives an Advertise message that includes a Preference option with
   a preference value of 255, the client immediately begins a client-
   initiated message exchange (as described in section 18) by sending a
   Request message to the server from which the Advertise message was
   received."

So although probably undesired the client behaves correctly. Now if the server had a lower preference as 255 we could actually wait for the second advert and simply put a higher administrative preference on the bigger prefix but in the current situation preferring the server with the /60 would probably violate the RFC.

**Comment by dtaht** [comment]
well, this worked on cerowrt 3.10.50-1.

**Comment by sbyx** [comment]
Maybe, I'm just saying this is not a bug. The client is RFC-compliant (the old behavior probably was not) and Comcast is actually at fault due to their server configuration.

I can try to find a compromise here, but I'd rather not explicitly break RFC-compliance to work-around a specific ISP configuration if I don't have to.

**Comment by dtaht** [comment]
From reading the rfc, you appear to be correct. Sigh. Bringing in my usual top gun...

**Comment by sbyx** [comment]
This whole issue probably belongs in https://github.com/sbyx/odhcp6c instead anyway.

I could add a special user option that overrides the behavior and actively violates the RFC, but it will not be enabled by default.

IIRC I read in the forums at some point that the behavior was different if you don't request a specific prefix length (option reqprefix unset) but don't know if that still is or ever was accurate.

@jbrzozowski any comments from your side?

**Comment by dtaht** [comment]
yes, well, I got confused 'cause I also have issues on dhcp...

https://dev.openwrt.org/ticket/19603#comment:1

**Comment by dtaht** [comment]
Sorry for filing on the wrong thing for this...

But anyway, you know whose code is faster to patch :), and violating the RFC is apparently what we were doing (to get something that worked)... Would merely ignoring the preference option suffice?

**Comment by dtaht** [comment]
Is there a way to move a ticket to another place? (and/or should I open another bug on the dhcpv4 solicit/reply but ignore I am pointing to above?)

**Comment by sbyx** [comment]
The DHCPv4 is a different issue since its a different program (busybox udhcpc). So let's keep v4 in the openwrt ticket. Also let's move the discussion to:
https://github.com/sbyx/odhcp6c/issues/34

**Comment by jbrzozowski** [comment]
While we are in the process of renumbering some IPv6 blocks this has not been done nationwide.  So I doubt this is a variable.  I will look into if the pair of DHCP server have a mismatched configuration.  As part of the upgrade @dtaht did anything else change?  DUID?  If you downgrade does it work.

**Comment by sbyx** [comment]
i just checked the dhcpv6 client code and if i did not overlook anything the election logic hasn't changed since late 2013, so if there were no side effects of other commits I suspect something else is going on here.

**Comment by dtaht** [comment]
@jbrzozowski is there a forum better than github to use for interacting with you?

I plan to resume testing some ipv6 related stuff in the next few weeks.

**Comment by jbrzozowski** [comment]
@dtaht are we all sorted out here?  Did this get resolved?

**Comment by dtaht** [comment]
@jbrzozowski : I have not had a chance to resume testing.

**Comment by sbyx** [comment]
@jbrzozowski this particular issue here and the one over in https://github.com/sbyx/odhcp6c/issues/34 are solved as far as i am concerned.

**Comment by dtaht** [comment]
I will attempt to confirm in the next 2 weeks.
