### ISSUE TITLE
Support an option like dnsmasq --force-fast-ra

### ISSUE THREAD

**Issue by cuviper** [openwrt/odhcpd#44]
I'm having an issue with my Samsung Galaxy S6 where the IPv6 preferred lifetime drops to zero while the device is asleep, because it apparently never see the RA to refresh it.  I found old bug reports on both [Android](https://code.google.com/p/android/issues/detail?id=32662) and [Samsung](http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=239890) -- this seems to be a long-standing and ignored issue.  I can even confirm that ping6 drops as soon as the device sleeps.

So, in the Android report I read that dnsmasq added a `--force-fast-ra` option [here](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=8d030462695410290e24d6ab19f0f242f0debb6a) which keeps spamming RAs every 10 seconds.  That way the device will get an RA not too long after waking up.  Crude, but effective.

Could odhcpd get a similar configuration option?  Perhaps as a custom override of MaxRtrAdvInterval?

**Comment by sbyx** [comment]
Acknowledged, though the dnsmasq "solution" doesn't address the problem really. Yes it allows for a fast recovery after turning on the screen however IPv6 is still broken while in standby (e.g. push-messages). I will try to add a feature which sends unicast RAs to known hosts, which should actually work-around better and is better for links like WiFi which generally do not play that well with MC.

**Comment by cuviper** [comment]
Thanks, I appreciate you trying to find an even better solution!

**Comment by sbyx** [comment]
Pleae see: https://lists.openwrt.org/pipermail/openwrt-devel/2015-July/034328.html

**Comment by sbyx** [comment]
That workaround doesn't seem to work, since the phones seem to ignore even much if not all of unicast traffic. I changed default lifetime to 65535 by default now if there is an address with suitable long lifetime, so ideally the phone can stay up for up to 18h without RAs. Additionally I added a parameter:
option ra_maxinterval <seconds> which lets you tune the maximum RA interval (real value might be lower depending on address lifetimes but not higher).

**Comment by cuviper** [comment]
I didn't get a chance to try the unicast RAs myself, but I won't bother since you already removed it.  I have loaded the current commit 053ca41 onto my router now, and can see the longer lifetime already.  I'll run with that for a while and see how the experience goes.  Hopefully I won't even need to bother with the max interval.  Thanks!

**Comment by cuviper** [comment]
So far, it has worked really well.  I haven't caught the phone's remaining lifetime any less than 60000, so maybe it is eventually picking up some RAs after all?  Whatever way it's staying alive, I'm happy -- thanks again!
