### ISSUE TITLE
sendmsg fails with EACCES

### ISSUE THREAD

**Issue by jech** [openwrt/odhcpd#45]
Trying to debug my proxy-NDP problems (see #15), it looks like odhcpd is failing to populate the neighbour cache:

```
setsockopt(11, SOL_SOCKET, SO_BINDTODEVICE, "wlan1\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
sendmsg(11, {msg_name(28)={sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2a01:e34:ec22:84a0:7973:8fc4:ac31:994d", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, msg_iov(1)=[{"\200\0\0\0\0\0\0\0", 8}], msg_controllen=0, msg_flags=0}, MSG_DONTWAIT) = -1 EACCES (Permission denied)
```

Sending on the "master" interface succeeds, but all the other interfaces fail with EACCES.

**Comment by jech** [comment]
Additional data point: this is not due to the firewall, since `ip6tables -I OUTPUT -j ACCEPT` didn't work around the issue.

**Comment by sbyx** [comment]
Looking into it, might have somethin to do with source-specific routes again, sigh.

**Comment by sbyx** [comment]
Should be fixed now. Seems kernel behavior has changed. Old workarounds don't work anymore. I have "solved" it differently now.

**Comment by jech** [comment]
Confirmed (ar71xx). Thanks a lot, I've got native IPv6 again!
