### ISSUE TITLE
Should I always need to get an IPv6 prefix from ISP in order to use odhcpd in any mode?

### ISSUE THREAD

**Issue by liudangyi** [openwrt/odhcpd#49]

**Comment by sbyx** [comment]
No, this is not necessary.

**Comment by liudangyi** [comment]
Thank you. So which mode should I use?

**Comment by sbyx** [comment]
What are you trying to do?

**Comment by liudangyi** [comment]
Well, while my router can visit IPv6.google.com out of box (with openwrt 14.09), the computer connected cannot even get an IPv6 address. I have tried relay / hybrid both, with variable combinations. But none of them work.

**Comment by liudangyi** [comment]
IMO, if correctly configured, lan should have the same IPv6 address as wan6. Is that right?
