### ISSUE TITLE
DHCPv6 relay-forward message sent through wrong socket

### ISSUE THREAD

**Issue by sodz** [openwrt/odhcpd#50]
When sending DHCPv6 relay-foward messages (dhcpv6.c:535), the used socket is bound to the slave interface (dhcpv6.c:63), while it is required to be sent through the master interface; thus the `sendmsg' system call returns EINVAL.
It seems that a UDP socket is also required on the master interface (dhcpv6.c:54), and the relay-forw message should be send through that socket. This solution works for me.

**Comment by sbyx** [comment]
Should be fixed in https://github.com/sbyx/odhcpd/commit/60bb0a1fc3e5c5c73fceedc26ebd7b8a2a608763 thanks.

**Comment by sodz** [comment]
But it was designed not to create such a socket on the master interface (dhcpv6.c:54):

```
if (enable && iface->dhcpv6 && !iface->master)
```

That should be fixed too, by deleting `&& !iface->master`.
