### ISSUE TITLE
Missing routing table entries for NDP relay

### ISSUE THREAD

**Issue by sodz** [openwrt/odhcpd#51]
Per default OpenWrt networking and system configurations, odhcpd cannot relay NDP "out of the box" in SLAAC or DHCPv6 (not -PD) configurations. Because the target address in NS (say 2001::abcd) is unreachable according to the routing table (actuallly there is no entries for any addresses other than link-local ones for the slave interface), the ping6 (ndp.c:210) fails with EACCES.
NDP works after I manually added the route to 2001::/64 (on-link) via slave interfaces.

**Comment by sbyx** [comment]
This should already be fixed in the current version, at least I pushed a fix few days ago.
