### ISSUE TITLE
Strange default for ra_management

### ISSUE THREAD

**Issue by jech** [openwrt/odhcpd#55]
Shouldn't ra_management default to 0 when the prefix length is 64, and 2 otherwise?

**Comment by sbyx** [comment]
Can you elaborate why? The default is to offer both SLAAC and stateful DHCPv6 by default. The latter is mainly for having hostname to IPv6 resolution since nobody likes to juggle around with v6 literals.

**Comment by jech** [comment]
> The default is to offer both SLAAC and stateful DHCPv6 by default. The
> latter is mainly for having hostname to IPv6 resolution since nobody
> likes to juggle around with v6 literals.

Ah, I see.  I still disagree, but at least I understand your logic.

-- Juliusz

**Comment by sbyx** [comment]
I agree with you as well, initially odhcpd did only do RAs and stateless DHCPv6 however the user community liked their stateful (v4isms) all too much so I had to give in. ;)
