### ISSUE TITLE
Infinite lease time is not supported

### ISSUE THREAD

**Issue by temp02** [openwrt/odhcpd#58]
Setting leasetime to infinite causes odhcpd to fail (only tested IPv6)
`uci set dhcp.lan.leasetime='infinite'`

It probably can be fixed by adding a conditional statement for IFACE_ATTR_LEASETIME 
https://github.com/sbyx/odhcpd/blob/master/src/config.c#L332

dnsmasq currently supports infinite lease time
http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

Infinite lease time is represented by a time value of 0xffffffff (uint32) according to RFC
DHCPv4: https://tools.ietf.org/html/rfc2131#section-3.3
DHCPv6: https://tools.ietf.org/html/rfc3315#section-5.6

**Comment by dedeckeh** [comment]
@temp02 Support for infinite leasetime has been added in commit https://git.lede-project.org/?p=project/odhcpd.git;a=commit;h=6c3bc0141dacc88992583d6f2cdc8a360df7422d
