### ISSUE TITLE
Missing possibility to make exceptions for specific devices under SLAAC 

### ISSUE THREAD

**Issue by grzchr15** [openwrt/odhcpd#69]
I use openwrt to deliver IPv6 addresses to my network. As i understand Android devices donot use DHCPv6, only SLAAC. But i donot want to give all my Android devices a IPv6 connectivity. So i need to exclude some devices from SLAAC. What options do we have ore need to implement?

**Comment by sbyx** [comment]
Unfortunately SLAAC is all or nothing, you cannot differentiate between individual devices. All devices on the link receive the same information.
