### ISSUE TITLE
Request: Add configurable RDNSS Field to RA

### ISSUE THREAD

**Issue by cvmiller** [openwrt/odhcpd#86]
odhcpd advertises the link-local of the router as the RDNSS in the RA. However, this often is useless to the client, since there is no scope (every interface has a link-local).

Clients like Android and ChromeOS do NOT do DHCPv6, but instead rely on SLAAC for addressing and RDNSS (from the RA).

Request user configurable RDNSS in odhcpd (as it has replaced radvd, which had this feature).

**Comment by kesslerm** [comment]
You can set DNS server addresses (e.g. the ULA address of the router) in the configuration file. See https://github.com/sbyx/odhcpd/blob/e63a2837acfaf54c97a9db466bf485e9f7024fe8/README#L90.

Any servers in the `dns` list will be sent in _rdnss_ options in the RA.

**Comment by cvmiller** [comment]
Thanks Kesslerm.
I gave it a try, and it works as stated. I do find the documentation a bit confusing, as it _seemed_ like the 'dns' and 'domain' options only applied to DHCPv6, and not to RAs. 

Would it be possible to update the language on the documentation to be more explicit that these options control not only DHCP, but also RAs?

thanks again.

Craig...

**Comment by dsanke** [comment]
have the same problem like cvmiller.
the 'dns' and 'domain' options only applied to DHCPv6, and not to RAs.

**Comment by dedeckeh** [comment]
Technically there's nothing wrong with using IPv6 link local address as DNS server unless buggy clients cannot handle IPv6 link local addresses as DNS server as an interface scope needs to be applied for link local IPv6 addresses.
The odhcpd version used in Lede trunk uses now by default ULA or global IPV6 addresses as IPv6 DNS server; if no such IPv6 addresses are available it falls back to the IPv6 link local address (https://git.lede-project.org/?p=project/odhcpd.git;a=commit;h=3d9f4067d56660a2c75ab2ce9b801ae1a4ff4cde)

**Comment by cvmiller** [comment]
Thanks, I agree that there are clients which can accept a link-local address correctly (they append the interface at the end, e.g.` fe80::1234:5678:9012:3456%eth0`) But that is up to the client, and there are poor implementations out there.

Using a ULA or GUA is a good option, thanks.
