### ISSUE TITLE
odhcpd not sending RAs

### ISSUE THREAD

**Issue by brianjmurrell** [openwrt/odhcpd#90]
I have an OpenWRT BB router (I know, I need to update) that has been working for many many months, untouched and now all of a sudden odhcpd is not sending out RAs other than when the router is rebooted.

Even restarting odhcpd doesn't send any RA's and Router Solicitations are not being responded to.

Clearly something has changed to make this start happening but it is not configuration related.  I have not touched configuration since building this router back when BB was released.

I'm hoping I can get some indication about what would cause odhcpd to not send RAs.

Shouldn't it be sending them periodically, even when not solicited by RS's?  If so, what could make it stop doing that.

For posterity:

```
# cat /etc/config/dhcp 

config dnsmasq
    option domainneeded '1'
    option boguspriv '1'
    option filterwin2k '0'
    option localise_queries '1'
    option rebind_protection '1'
    option rebind_localhost '1'
    option local '/lan/'
    option domain 'ilinx'
    option expandhosts '1'
    option nonegcache '0'
    option authoritative '1'
    option readethers '1'
    option leasefile '/tmp/dhcp.leases'
    option resolvfile '/tmp/resolv.conf.auto'

config dhcp 'lan'
    option interface 'lan'
    option dhcpv6 'server'
    option ra 'server'
    option ra_management '1'
    option start '100'
    option limit '150'
    option leasetime '12h'
    list dns 'fd31:aeb1:48df:0:214:d1ff:fe13:45ac'

config dhcp 'wan0'
    option interface 'wan0'
    option ignore '1'

config dhcp 'wan1'
    option ignore '1'
    option interface 'wan1'
    option dynamicdhcp '0'

config odhcpd 'odhcpd'
    option maindhcp '0'
    option leasefile '/tmp/hosts/odhcpd'
    option leasetrigger '/usr/sbin/odhcpd-update'
```

**Comment by dtaht** [comment]
This might have some bearing on the issues I was seeing: https://bugs.lede-project.org/index.php?do=details&task_id=388

**Comment by brianjmurrell** [comment]
@dtaht It's weird that it just all of a sudden started happening with no firmware changes or configuration changes at all.  I ended up resolving it with a major openwrt version upgrade which was needed anyway.

In the typical trading one bag of bugs for another when doing upgrades, now I have a problem that OpenWRT doesn't see neighbour discovery traffic from the LAN unless I keep the _br-lan_ port in promiscuous mode.  It's like multicast is just not working or something.

At least that problem has a simple work-around unlike the problem detailed in this ticket.

**Comment by brianjmurrell** [comment]
Not seeing this any more.
