### ISSUE TITLE
Feature Request: DHCPv6 Lease Time config

### ISSUE THREAD

**Issue by cvmiller** [openwrt/odhcpd#93]
There is a config value for DHCPv4 lease time, but not for DHCPv6.

With ISPs changing prefixes every time the router reconnects, the long lease time leaves old prefixes on the end stations. It would be beneficial to have the ability to put in a shorter lease time (perhaps as short as 10 minutes) for DHCPv6 lease time.

**Comment by EricLuehrsen** [comment]
It looks like the LEDE fork already implemented that `leasetime` applies to **DHCP v4** and **v6** equally, which makes sense. It would be nice if this also applied to the **RA lifetime** on prefixes and routes, so WiFi heavy-roaming environments could set them down to an hour.

**Comment by cvmiller** [comment]
This is good to know. I agree with the RA lifetime comment, perhaps it will also be added. thanks.

**Comment by dtaht** [comment]
I agree the ra lifetime idea would be nice also. I was also observing a route retract here: https://bugs.lede-project.org/index.php?do=details&task_id=388

which was wreaking havoc.

**Comment by dedeckeh** [comment]
Fixed in commit https://git.openwrt.org/?p=project/odhcpd.git;a=commit;h=6db312a698e920ff61505ef1f42469880829774d

**Comment by dtaht** [comment]
Thx!
