### ISSUE TITLE
UCI "leasefile" location is not initialized

### ISSUE THREAD

**Issue by EricLuehrsen** [openwrt/odhcpd#95]
odhcpd is designed to be directly tied to the UCI format. However if `leasefile` directory does not exist, then odhcpd does not create it. odhcpd should create the `leasefile` directory and blank file on startup as given by the user. It could be filtered to only allow `/tmp/...`, `/var/lib/odhcpd/...`, `/usr/local/...` or other normal location per std. file hierarchy.

The file `/tmp/hosts/odhcpd` is created by `/etc/init.d/dnsmasq`. `/tmp/` is typically mapped to RAM in OpenWrt/LEDE, so its all gone at boot. It is altogether reasonable that someone might remove package dnsmasq for Unbound or Bind.  It is also reasonable for someone to map away from `/tmp/hosts/odhcpd` (tmpfs, RAM) and perhaps to `/var/lib/odhcpd` (external sD or something).

**Comment by dedeckeh** [comment]
@EricLuehrsen Creation of leasefile directory is fixed in commit https://git.lede-project.org/?p=project/odhcpd.git;a=commit;h=0572d1abbadf7b955f2788d04ca3d00f45963e6a

**Comment by EricLuehrsen** [comment]
@dedeckeh again thanks. (kept open pending maintenance issue...)
